CREATE DATABASE IF NOT EXISTS classflow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE classflow;

CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 email VARCHAR(191) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 role ENUM('admin','teacher','student') NOT NULL,
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS courses (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code VARCHAR(40) NOT NULL UNIQUE,
 title VARCHAR(191) NOT NULL,
 description TEXT NULL,
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sections (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 course_id BIGINT UNSIGNED NOT NULL,
 teacher_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(120) NOT NULL,
 enrollment_code VARCHAR(32) NOT NULL UNIQUE,
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_sections_course FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE RESTRICT,
 CONSTRAINT fk_sections_teacher FOREIGN KEY(teacher_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS enrollments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 section_id BIGINT UNSIGNED NOT NULL,
 student_id BIGINT UNSIGNED NOT NULL,
 enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_enrollments_section_student(section_id,student_id),
 CONSTRAINT fk_enrollments_section FOREIGN KEY(section_id) REFERENCES sections(id) ON DELETE RESTRICT,
 CONSTRAINT fk_enrollments_student FOREIGN KEY(student_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS materials (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 section_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(191) NOT NULL,
 description TEXT NULL,
 file_path VARCHAR(255) NOT NULL,
 original_name VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_materials_section FOREIGN KEY(section_id) REFERENCES sections(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS assignments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 section_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(191) NOT NULL,
 instructions TEXT NOT NULL,
 due_at DATETIME NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_assignments_section FOREIGN KEY(section_id) REFERENCES sections(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS submissions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 assignment_id BIGINT UNSIGNED NOT NULL,
 student_id BIGINT UNSIGNED NOT NULL,
 file_path VARCHAR(255) NOT NULL,
 original_name VARCHAR(255) NOT NULL,
 submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_submission_assignment_student(assignment_id,student_id),
 CONSTRAINT fk_submissions_assignment FOREIGN KEY(assignment_id) REFERENCES assignments(id) ON DELETE RESTRICT,
 CONSTRAINT fk_submissions_student FOREIGN KEY(student_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS grades (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 submission_id BIGINT UNSIGNED NOT NULL UNIQUE,
 teacher_id BIGINT UNSIGNED NOT NULL,
 score DECIMAL(6,2) NOT NULL,
 feedback TEXT NULL,
 status ENUM('draft','released') NOT NULL DEFAULT 'draft',
 graded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 released_at TIMESTAMP NULL DEFAULT NULL,
 CONSTRAINT ck_grade_score CHECK (score >= 0 AND score <= 100),
 CONSTRAINT fk_grades_submission FOREIGN KEY(submission_id) REFERENCES submissions(id) ON DELETE RESTRICT,
 CONSTRAINT fk_grades_teacher FOREIGN KEY(teacher_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;
