<?php
namespace App\Controllers;
use App\Core\{DB,Security,View,Upload};
final class StudentController extends BaseController {
 private function section(int $id): array {$u=Security::requireRole('student');$s=DB::one('SELECT s.*,c.title AS course_title,c.code AS course_code FROM sections s JOIN courses c ON c.id=s.course_id JOIN enrollments e ON e.section_id=s.id WHERE s.id=? AND e.student_id=?',[$id,$u['id']]);if(!$s) Security::abort(403);return $s;}
 public function index(): void {$u=Security::requireRole('student');View::render('student/index',['title'=>'My learning','sections'=>DB::all('SELECT s.*,c.code,c.title FROM enrollments e JOIN sections s ON s.id=e.section_id JOIN courses c ON c.id=s.course_id WHERE e.student_id=? ORDER BY e.id DESC',[$u['id']])]);}
 public function enroll(): void {$this->requirePost();$u=Security::requireRole('student');$this->execute(function()use($u){$code=strtoupper($this->required('enrollment_code',32));$s=DB::one('SELECT s.id FROM sections s JOIN courses c ON c.id=s.course_id JOIN users t ON t.id=s.teacher_id WHERE s.enrollment_code=? AND s.is_active=1 AND c.is_active=1 AND t.is_active=1',[$code]);if(!$s) throw new \RuntimeException('Enrollment code not found or section inactive.');DB::exec('INSERT IGNORE INTO enrollments(section_id,student_id) VALUES(?,?)',[$s['id'],$u['id']]);Security::redirect('/student/sections/'.$s['id'],'Section enrolled.');},'/student');}
 public function detail(int $id): void {$s=$this->section($id);$u=Security::user();View::render('student/section',['title'=>'Section: '.$s['name'],'s'=>$s,'materials'=>DB::all('SELECT * FROM materials WHERE section_id=? ORDER BY id DESC',[$id]),'assignments'=>DB::all("SELECT a.*,sb.id AS submission_id,sb.submitted_at,g.score,g.feedback,g.status FROM assignments a LEFT JOIN submissions sb ON sb.assignment_id=a.id AND sb.student_id=? LEFT JOIN grades g ON g.submission_id=sb.id AND g.status='released' WHERE a.section_id=? ORDER BY a.id DESC",[$u['id'],$id])]);}
 public function submit(): void {$this->requirePost();$u=Security::requireRole('student');$a=DB::one('SELECT * FROM assignments WHERE id=?',[$this->id('assignment_id')]);if(!$a) Security::abort();$s=$this->section((int)$a['section_id']);$fallback='/student/sections/'.$s['id'];$this->execute(function()use($u,$a,$fallback){if($a['due_at']!==null && strtotime($a['due_at']) < time()) throw new \RuntimeException('This assignment is past its deadline.');if(DB::one('SELECT id FROM submissions WHERE assignment_id=? AND student_id=?',[$a['id'],$u['id']])) throw new \RuntimeException('You have already made your final submission.');$upload=Upload::save('file');try{DB::exec('INSERT INTO submissions(assignment_id,student_id,file_path,original_name) VALUES(?,?,?,?)',[$a['id'],$u['id'],$upload['path'],$upload['name']]);}catch(\Throwable $e){@unlink(dirname(__DIR__,2).'/storage/uploads/'.$upload['path']);throw $e;}Security::redirect($fallback,'Final submission received.');},$fallback);}
 public function downloadMaterial(int $id): void {$m=DB::one('SELECT * FROM materials WHERE id=?',[$id]);if(!$m) Security::abort();$this->section((int)$m['section_id']);Upload::send($m['file_path'],$m['original_name']);}
 public function downloadSubmission(int $id): void {$u=Security::requireRole('student');$sb=DB::one('SELECT sb.*,a.section_id FROM submissions sb JOIN assignments a ON a.id=sb.assignment_id WHERE sb.id=? AND sb.student_id=?',[$id,$u['id']]);if(!$sb) Security::abort(403);$this->section((int)$sb['section_id']);Upload::send($sb['file_path'],$sb['original_name']);}
}
