<?php
namespace App\Controllers;
use App\Core\{DB,Security,View,Upload};
final class TeacherController extends BaseController {
 private function section(int $id): array {$u=Security::requireRole('teacher');$s=DB::one('SELECT s.*,c.title AS course_title,c.code AS course_code FROM sections s JOIN courses c ON c.id=s.course_id WHERE s.id=? AND s.teacher_id=?',[$id,$u['id']]);if(!$s) Security::abort(403);return $s;}
 private function assignment(int $id): array {$a=DB::one('SELECT * FROM assignments WHERE id=?',[$id]);if(!$a) Security::abort();$this->section((int)$a['section_id']);return $a;}
 public function index(): void {$u=Security::requireRole('teacher');View::render('teacher/index',['title'=>'My sections','sections'=>DB::all('SELECT s.*,c.code,c.title FROM sections s JOIN courses c ON c.id=s.course_id WHERE s.teacher_id=? ORDER BY s.id DESC',[$u['id']])]);}
 public function detail(int $id): void {$s=$this->section($id);View::render('teacher/section',['title'=>'Section: '.$s['name'],'s'=>$s,'materials'=>DB::all('SELECT * FROM materials WHERE section_id=? ORDER BY id DESC',[$id]),'assignments'=>DB::all('SELECT * FROM assignments WHERE section_id=? ORDER BY id DESC',[$id]),'roster'=>DB::all('SELECT u.name,u.email,e.enrolled_at FROM enrollments e JOIN users u ON u.id=e.student_id WHERE e.section_id=? ORDER BY u.name',[$id])]);}
 public function material(): void {$this->requirePost();$s=$this->section($this->id('section_id'));$this->execute(function() use($s){$title=$this->required('title');$description=\input('description');$upload=Upload::save('file');try{DB::exec('INSERT INTO materials(section_id,title,description,file_path,original_name) VALUES(?,?,?,?,?)',[$s['id'],$title,$description,$upload['path'],$upload['name']]);}catch(\Throwable $e){@unlink(dirname(__DIR__,2).'/storage/uploads/'.$upload['path']);throw $e;}Security::redirect('/teacher/sections/'.$s['id'],'Material uploaded.');},'/teacher/sections/'.$s['id']);}
 public function assignmentSave(): void {$this->requirePost();$s=$this->section($this->id('section_id'));$this->execute(function()use($s){$id=(int)($_POST['id']??0);$title=$this->required('title');$instructions=$this->required('instructions',20000);$due=\input('due_at');if($due!=='' && !\DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$due)) throw new \RuntimeException('Invalid deadline.');$due=$due?str_replace('T',' ',$due).':00':null;
 if($id){$a=$this->assignment($id);if((int)$a['section_id']!==(int)$s['id']) Security::abort(403);DB::exec('UPDATE assignments SET title=?,instructions=?,due_at=? WHERE id=?',[$title,$instructions,$due,$id]);}
 else DB::exec('INSERT INTO assignments(section_id,title,instructions,due_at) VALUES(?,?,?,?)',[$s['id'],$title,$instructions,$due]);Security::redirect('/teacher/sections/'.$s['id'],'Assignment saved.');},'/teacher/sections/'.$s['id']);}
 public function submissions(int $id): void {$a=$this->assignment($id);$items=DB::all('SELECT sb.*,u.name AS student_name,g.id AS grade_id,g.score,g.feedback,g.status FROM submissions sb JOIN users u ON u.id=sb.student_id LEFT JOIN grades g ON g.submission_id=sb.id WHERE sb.assignment_id=? ORDER BY sb.submitted_at DESC',[$id]);View::render('teacher/submissions',['title'=>'Submissions','a'=>$a,'items'=>$items]);}
 public function grade(): void {$this->requirePost();$u=Security::requireRole('teacher');$submission=$this->id('submission_id');$sb=DB::one('SELECT sb.id,sb.assignment_id,a.section_id FROM submissions sb JOIN assignments a ON a.id=sb.assignment_id WHERE sb.id=?',[$submission]);if(!$sb) Security::abort();$this->section((int)$sb['section_id']);$fallback='/teacher/assignments/'.$sb['assignment_id'].'/submissions';$this->execute(function()use($u,$submission,$fallback){$score=\input('score');if(!is_numeric($score)||(float)$score<0||(float)$score>100) throw new \RuntimeException('Score must be between 0 and 100.');$status=\input('status');if(!in_array($status,['draft','released'],true)) throw new \RuntimeException('Invalid grade status.');$feedback=\input('feedback',20000);
 DB::exec("INSERT INTO grades(submission_id,teacher_id,score,feedback,status,released_at) VALUES(?,?,?,?,?,IF(?='released',NOW(),NULL)) ON DUPLICATE KEY UPDATE teacher_id=VALUES(teacher_id),score=VALUES(score),feedback=VALUES(feedback),status=VALUES(status),released_at=IF(VALUES(status)='released',COALESCE(released_at,NOW()),NULL),graded_at=CURRENT_TIMESTAMP",[$submission,$u['id'],(float)$score,$feedback,$status,$status]);Security::redirect($fallback,'Grade saved.');},$fallback);}
 public function downloadMaterial(int $id): void {$m=DB::one('SELECT * FROM materials WHERE id=?',[$id]);if(!$m) Security::abort();$this->section((int)$m['section_id']);Upload::send($m['file_path'],$m['original_name']);}
 public function downloadSubmission(int $id): void {$sb=DB::one('SELECT sb.*,a.section_id FROM submissions sb JOIN assignments a ON a.id=sb.assignment_id WHERE sb.id=?',[$id]);if(!$sb) Security::abort();$this->section((int)$sb['section_id']);Upload::send($sb['file_path'],$sb['original_name']);}
}
